### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by bond0O7** [Noah11012/result-for-cpp#3]
You can use std::variant instead

**Comment by Noah11012** [comment]
At the time the repository was made I was someone who programmed in some amount of Rust and I was interested in the Result type. I thought it was something that could be brought over to C++ to make code more readable. For a while I have not updated this repo because I find no interest in it anymore.

**Comment by bond0O7** [comment]
Yeah
it's a great idea
I hope the standard adopt such a mechanism
